### ISSUE TITLE
Unsupported RegexMatch expression

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#264]
Query like this: `WHERE name =~ "Hello"`

**Comment by dwitry** [comment]
[Merged](https://github.com/opencypher/cypher-for-gremlin/commit/cba6edcb54e71fe66363e4e05409e9260f9bfd9a) to [tinkerpop334](https://github.com/opencypher/cypher-for-gremlin/tree/tinkerpop334) branch as well.

**Comment by mad** [comment]
JanusGraph support custom Text.REGEX predicate that can be translated to backend specified query like a lucene RegexpQuery

It may implemented using the GremlinRewriter?

**Comment by dwitry** [comment]
It would be straightforward to implement using rewriter, however it would require to create separate module in Cypher for Gremlin, because [Text](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java) is located in `janusgraph-core`. We try to avoid implementation specific dependencies in Cypher for Gremlin translation module.
