### ISSUE TITLE
Error in Translation

### ISSUE THREAD

**Issue by rifuller** [opencypher/cypher-for-gremlin#294]
First of all - thank you for such a useful library.  My team is more familiar with Cypher but I've built my project using a CosmosDB backend and this allows them to use their existing knowledge.

So, I have a simple application for converting a CYPHER query to Gremlin.

```scala
object Main extends App {
    val input = "MATCH (m:Machine)-[e:Has {storeName: \"CA\"}]->(c:Certificate) \nWHERE m.name =~ \"*.domain\"\nRETURN m.name,e.storeName,c.name,c.thumbprint"
    val facade = new TranslationFacade()
    println(facade.toGremlinGroovy(input))
}
```

this outputs:

```
g.V().as('m').hasLabel('Machine').has('name', cypherRegex('*.domain')).outE('Has').as('e').has('storeName', eq('CA')).inV().as('c').hasLabel('Certificate').select('m', 'e', 'c').project('m.name', 'e.storeName', 'c.name', 'c.thumbprint').by(__.select('m').choose(__.values('name'), __.values('name'), __.constant('  cypher.null'))).by(__.select('e').choose(neq('  cypher.null'), __.choose(__.values('storeName'), __.values('storeName'), __.constant('  cypher.null')))).by(__.select('c').choose(neq('  cypher.null'), __.choose(__.values('name'), __.values('name'), __.constant('  cypher.null')))).by(__.select('c').choose(neq('  cypher.null'), __.choose(__.values('thumbprint'), __.values('thumbprint'), __.constant('  cypher.null'))))
```

When I run that query on CosmosDB I get this error:
`Gremlin Query Compilation Error: Unable to resolve symbol 'cypherRegex' in the current context`

Is this a bug or unsupported?

**Comment by dwitry** [comment]
Hello @rifuller,

thank you, we are happy to know that Cypher for Gremlin is useful for your team.

Because native Gremlin has [no predicate](http://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates) for Regex match,  `cypherRegex` is [custom predicate](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-extensions) that extends Gremlin functionality. Unfortunately, custom functions and predicates are not [supported](https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-support#gremlin-steps) in Cosmos DB.

This is actually a shortcoming that error about `cypherRegex` is not shown on the translation stage, as it happens with other custom predicates. I will improve query validation.

Maybe for your requirement could be addressed with text predicates (`startingWith`, `containing`...)? According to [Cosmos DB Team statement](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/34469122-add-support-for-text-search-predicates) it was recently implemented, however, I was not able to get it working:

```
gremlin> g.V().has('name', TextP.startingWith('ma'))
Gremlin Query Compilation Error: Unable to resolve symbol 'TextP' in the current context. @ line 1, column 19.
```

Please notify me if it works in your case, I might be missing something.

By the way, to adapt query to other [Cosmos DB specifics](https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations#cosmos-db), it is recommended to use `cosmosDb` [flavor](https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations#flavors):

```scala
  val input =
    "MATCH (m:Machine)-[e:Has {storeName: \"CA\"}]->(c:Certificate) \nWHERE m.name =~ \"*.domain\"\nRETURN m.name,e.storeName,c.name,c.thumbprint"
  val ast = CypherAst.parse(input)
  val translator = Translator.builder.gremlinGroovy.build(TranslatorFlavor.cosmosDb)
  println(ast.buildTranslation(translator))
```

Please let me know if you have any other questions, or close this issue.

**Comment by rifuller** [comment]
There are only a couple of pieces of that translated query at least that custom predicates: `cypherRegex` and `cypher.null`.  I replaced the first with `TextP.endingWith` (and removed the '*') and replaced the latter with an empty string and then it does run!  Is replacing `cypher.null` with that the right option here?

`c.name` is an optional field so I just need to confirm that records are returned where that is empty/null still.

I'll update my tool with those tweaks, and set it to use the CosmosDB flavor.

**Comment by dwitry** [comment]
`"  cypher.null"` is just a String [representing null in Gremlin](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-extensions#null-handling). It does not require custom plugin, so my recommendation would be to leave it as it is.

Thank you for mentioning that `TextP.*` is working in your case. I've created a new Cosmos DB instance (`TextP.*` was not working for previously created instances for some reason). Can confirm that Cypher `STARTS WITH` / `ENDS WITH` / `CONTAINS` are now working in Cosmos DB, so it should be possible to use your tool without additional tweaks.

**Comment by dwitry** [comment]
@rifuller, closing issue after a week of inactivity. Don't hesitate to open a new issue if you have any more questions.
