### ISSUE TITLE
support `:remote console`

### ISSUE THREAD

**Issue by zhiboz** [opencypher/cypher-for-gremlin#4]
with `:remote console`, one can sends all Gremlin queries to the remote connection without prefixing `:>`, however, it is not supported by `cypher-for-gremlin` yet. below is the error message.

```groovy
gremlin> :remote console
==>The org.opencypher.gremlin.console.jsr223.CypherRemoteAcceptor@78307a56 is not compatible with 'connect' - use ':>' instead
```

it'd be nice to support `:remote console`.

**Comment by disolovyov** [comment]
Resolved by #84

**Comment by zhiboz** [comment]
great, thanks! one minor issue

this works in local mode

```
:> match (n:person) return count(n)
```

but not in the remote mode. it seems to expect a upper case `R` for the keyword `return` to work 

so this doesn't work

```
match (n:person) return count(n)
```

but this does

```
match (n:person) Return count(n)
```

**Comment by ilyin371** [comment]
Using ":submit" (shorthand ":>") command Gremlin Console passes a script line to Console Plugin at once. In the remote mode the console first tries to parse a script line as Groovy in order to determine if it's a multiline script, before passing it to the Console Plugin for evaluation. Cypher query might not be a valid Groovy, so it fails. 

Sorry,  looks like at this point there is no way for us to workaround such Console behavior.
